name: Unit Tests

on:
  push:
    branches:
      - feature/*

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4 

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore application dependencies
        run: dotnet restore 

      - name: Build application
        run: dotnet build

      - name: Run unit-tests
        run: dotnet test  
